version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "9090:9090"
    environment:
     - DUCKDB_POOL_SIZE=5
     - VITE_SESSION_SECRET=$VITE_SESSION_SECRET
    networks:
      - fiddle-network

  client:
    build:
      context: ./client
      args:
      - VITE_SESSION_SECRET=$VITE_SESSION_SECRET
    ports:
      - "80:8080"
    networks:
      - fiddle-network
    environment:
     - NODE_ENV=production

networks:
  fiddle-network:
    driver: bridge
