version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "9090:9090"
    environment:
     - DUCKDB_POOL_SIZE=5
    networks:
      - fiddle-network

  client:
    build: ./client
    ports:
      - "8080:8080"
    networks:
      - fiddle-network

networks:
  fiddle-network:
    driver: bridge
