version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "9090:9090"
    environment:
     - DUCKDB_POOL_SIZE=5
    networks:
      - fiddle-network
    secrets:
       - VITE_SESSION_SECRET

  client:
    build: ./client
    ports:
      - "8080:8080"
    networks:
      - fiddle-network
    secrets:
       - VITE_SESSION_SECRET

networks:
  fiddle-network:
    driver: bridge

secrets:
  VITE_SESSION_SECRET:
    external: true
    name: ${{ secrets.VITE_SESSION_SECRET }}
