name: Deploy api and client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'api/**'
      - '.github/workflows/deploy-api-client.yml'
      - 'docker-compose.yaml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'

permissions:
  actions: write
  checks: read
  deployments: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: substrait-fiddle

    - name: Copy files to remote repository
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST_DNS }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        rm: true
        source: "substrait-fiddle/*"
        target: ~/deployment

    - name: Deploy the docker-compose
      uses: appleboy/ssh-action@v1.0.3
      env:
        VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
      with:
        host: ${{ secrets.DEPLOY_HOST_DNS }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        envs: VITE_SESSION_SECRET
        script: |
          export VITE_SESSION_SECRET=$VITE_SESSION_SECRET
          cd ~/deployment/substrait-fiddle
          docker-compose stop
          docker-compose rm -f
          docker-compose build --no-cache
          docker-compose up -d

    - name: Cleanup unused docker images, volumes and build cache
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST_DNS }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          docker container prune -f
          docker image prune -f
          docker volume prune -f
          docker builder prune -f
