name: Vitest

on: [push]

env:
  VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout api service
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and deploy backend
      working-directory: api
      run: |
        python -m ensurepip --default-pip
        pip install -r requirements.txt
        uvicorn app:app --port 9090 & bash -c 'while ! curl -s http://localhost:9090 > /dev/null; do sleep 1; done'
    
    - name: Checkout client service
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: client
      run: npm ci
    - name: Run tests
      working-directory: client
      run: npm test
