name: Test

on: [push]

env:
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5

jobs:
  Pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: 4.4

    - name: Install dependencies
      working-directory: api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: api
      run: pytest test.py
