name: Vitest

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and deploy backend
      working-directory: api
      run: |
        python -m ensurepip --default-pip
        pip install -r requirements.txt
        uvicorn app:app --port 9090 & bash -c 'while ! curl -s http://localhost:9090 > /dev/null; do sleep 1; done'
    
    - run: cd client/
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: |
        npm install
        npm run test

