name: Test

on: [push]

jobs:
  Pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./api/requirements.txt

    - name: Run tests
      run: pytest ./api/test.py
